# Generated by Django 4.1.7 on 2023-03-10 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backupaccountnumber",
            options={"verbose_name": "备份表", "verbose_name_plural": "备份列表"},
        ),
    ]
