# Generated by Django 4.1.7 on 2023-03-10 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_options"),
        ("backup", "0002_alter_backupaccountnumber_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupWebUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("url_name", models.CharField(blank=True, max_length=255, null=True)),
                ("url_remarks", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.user",
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "备份网站表",
                "verbose_name_plural": "备份网站列表",
                "db_table": "Backup_Web_Url",
            },
        ),
    ]
