# Generated by Django 4.1.7 on 2023-04-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False)),
                ('cartoon_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mongo_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
