# Generated by Django 4.1.7 on 2023-04-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('iphone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户列表',
                'db_table': 'User_Model',
            },
        ),
    ]
