# Generated by Django 4.1.7 on 2023-03-10 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user", options={"verbose_name": "用户表", "verbose_name_plural": "用户列表"},
        ),
    ]
